### ISSUE TITLE
Project has MIT license but source has LPGLv3

### ISSUE THREAD

**Issue by ChartreuseK** [misc0110/libattopng#3]
In https://github.com/misc0110/libattopng/commit/7d8441aee14548aeb8dbf41ed253d0dd60234053 the license of the project (LICENSE) was changed from LGPLv3 to MIT, however both libattopng.c and libattopng.h still start with a LGPLv3 header. 

Is the library available under MIT as the main license file and the commit seem to suggest? Or is it available only under LPGLv3 as the source code would suggest?

**Comment by misc0110** [comment]
The library is available under MIT, I removed the comments in the files in b427234877f9cb530d91a10034454da679fa7a98
