### ISSUE TITLE
malloc() -> calloc()

### ISSUE THREAD

**Issue by 7890** [misc0110/libattopng#4]
valgrind tells that saving a png file can in some cases lead to "Use of uninitialised value".

Proposing to use calloc() instead of malloc() in libattopng_new():
https://github.com/misc0110/libattopng/blob/b427234877f9cb530d91a10034454da679fa7a98/libattopng.c#L79

Test program
```
#include <libattopng.h>
int main(int argc, char *argv[]) {
        libattopng_t *png = libattopng_new(10, 10, PNG_RGBA);
        libattopng_save(png, "/tmp/test.png");
        libattopng_destroy(png);
        return 0;
}
// valgrind -v ...
```

**Comment by misc0110** [comment]
Fixed in 6fdc9a8cb1f0b36e6f4d5986b818d37e4e2eccce
